algorithm: ppo
backend: np
description: n/a
env: Imitation
env_config:
  ankle_offsets:
  - -0.0
  - -0.0
  command:
    ang_vel_z:
    - 0.0
    - 0.0
    enabled: true
    lin_vel_x:
    - -0.2
    - 0.2
    lin_vel_y:
    - -0.1
    - 0.1
    vdes_duration: 7.0
  ctrl_dt: 0.02
  curriculum:
    enabled: false
    scale: 1.0
    scaling_iterations: 75.0
  domain_randomization:
    enabled: true
    obs_delay:
      accel:
      - 0
      - 1
      enabled: false
      gyro:
      - 0
      - 1
      qpos:
      - 0
      - 1
    params:
      body_com: 0.01
      dof_armature: 0.1
      dof_damping: 0.1
      dof_frictionloss: 0.1
      floor_friction: 0.4
      forcerange: 0.2
      gain_multiplier: 0.2
      timeconst: 0.2
      torso_com: 0.03
      torso_mass: 0.2
      z0: 0.02
  filter_tau: 0.04
  history_length: 5
  initialization:
    add_random_jt:
      enabled: false
      maxval: 0.08
      minval: -0.08
    add_random_yaw: false
    chance_default: 1.0
    random_jt_calibration:
      enabled: false
      maxval: 0.0
      minval: -0.0
    strategy: random-with-zero
    vdes:
    - 0.0
    - 0.0
    - 0.0
  jt_scale: 0.5
  noise_scale: 1.0
  push:
    annulus_width: 0.1
    enabled: true
    major_lim: 5.0
    max_vdes:
    - 0.1
    - 0.06
    - 0.01
    minor_lim: 5.0
    nopush_duration: 9.0
    push_duration: 0.6
  reward:
    sigmas:
      base_quat_tracking: 0.03
      base_vel_tracking: 0.05
      base_xyz_tracking: 0.001
      gait_tracking: 0.13
      global_xy_tracking: 0.05
      global_z_tracking: 0.13
      minimize_energy: 60.0
      vel_residual_rate: 0.08
      vel_residual_size: 0.003
    weights:
      alive: 0.0
      base_quat_tracking: 1.0
      base_vel_tracking: 0.0
      base_xyz_tracking: 3.0
      foot_contact: 0.0
      gait_tracking: 1.0
      global_xy_tracking: 0.0
      global_z_tracking: 0.0
      minimize_energy: 0.5
      res_jt_rate: -0.2
      vel_residual_rate: 0.2
      vel_residual_size: 0.75
  sim_dt: 0.004
  start_stance: either
  termination:
    enabled: true
  terrain: flat
  tracking: position
  vel_scale: 0.0
gaitlib_path: envs/bruce/gaits/BRUCE_GL_4bar_noarms_v1
git_hash: 6f6924d02349c3e120ca25f13afe181a58a33cbe
learning_params:
  network_params:
    policy_hidden_layer_sizes:
    - 256
    - 128
    - 64
    value_hidden_layer_sizes:
    - 256
    - 128
    - 64
  ppo_params:
    action_repeat: 1
    batch_size: 256
    clipping_epsilon: 0.2
    discounting: 0.97
    entropy_cost: 0.01
    episode_length: 2000
    learning_rate: 0.0003
    max_grad_norm: 1.0
    normalize_observations: false
    num_envs: 8192
    num_evals: 20
    num_minibatches: 32
    num_timesteps: 400000000
    num_updates_per_batch: 4
    reward_scaling: 1.0
    unroll_length: 32
name: test
robot: BRUCE
save_dir: icra2026-final/imitation
